const UPLOAD_URL = process.env.UPLOAD_URL || '';     // 节点自动上传到订阅器地址
const PROJECT_URL = process.env.PROJECT_URL || '';   // 自动保活地址 
const AUTO_ACCESS = process.env.AUTO_ACCESS || true; // 自动保活,默认开启，需要同时填写PROJECT_URL变量
const FILE_PATH = process.env.FILE_PATH || './.npm'; // 运行路径 
const SUB_PATH = process.env.SUB_PATH || 'sub';      // 订阅token       
const UUID = process.env.UUID || '79c4790a-52a0-4f0a-b724-abdbe3190073'; // UUID
const NEZHA_SERVER = process.env.NEZHA_SERVER || ''; // 哪吒v1: nezha.xxx.com:8008  哪吒v0: nezha.xxx.com      
const NEZHA_PORT = process.env.NEZHA_PORT || '';     // 哪吒v1留空     
const NEZHA_KEY = process.env.NEZHA_KEY || '';       // 哪吒v1的NZ_CLIENT_SECRET或v0的agent密钥      
const ARGO_DOMAIN = process.env.ARGO_DOMAIN || 'idx.777171.xyz';   // 固定隧道域名，留空使用临时隧道     
const ARGO_AUTH = process.env.ARGO_AUTH || 'eyJhIjoiMTZjM2Q3ZWUyZjlmZmRiZmVlY2IzYTJlMThkMDE2ZjgiLCJ0IjoiZjE3YjYwNzctOTJjMi00NmU1LTkyNDctNjcxOTg4MTI5ZTE2IiwicyI6IlpUVXdPVEprT1RndE1qVTFOaTAwWlRKa0xXSm1PVFF0TVdKa1ptTmhOVGs0WVdWayJ9';       // 固定隧道密钥json或token，留空使用临时隧道,json获取地址：https://json.zone.id                        
const ARGO_PORT = process.env.ARGO_PORT || 8001;     // 隧道端口，使用token需在cloudflared设置和这里一致     
const CFIP = process.env.CFIP || 'cf.877774.xyz';    // 优选域名或优选ip       
const CFPORT = process.env.CFPORT || 443;            // 优选域名或优选ip对应端口      
const NAME = process.env.NAME || 'Appwrite';         // 节点名称       
